spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.126:9092
          zkNodes: 192.168.0.126:2181
          auto-create-topics: false
        bindings:
          outputChannelOne:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
#      default:
#        producer:
#          header-mode: embeddedHeaders
      bindings:
        outputChannelOne:
          destination: channelOne
          content-type: application/json
#  kafka:
#    bootstrap-servers: 192.168.0.126:9092 nejde ked toto setnem